apiVersion: v1
kind: Pod
metadata:
  name: tomcattest1
  labels:
    role: tomcattest1-role
    app: tomcattest1
spec:
  containers:
  - name: tomcattest1
    image: dineshrajwade/tomcat_new1:latest
    ports:
     - containerPort:8080
  
