kind: Deployment
apiVersion: apps/v1
metadata:
  name: testdeploy
  labels:
    city: chennai
spec:
  selector:
   matchLabels:
     region: south
  replicas: 1
  template:
    metadata:
     name: testpod
     labels:
      region: south
    spec:
     containers:
     - name: tomcattest1 
       image: dineshrajwade/tomcat_new1
